name: Release via file changes

on:
  pull_request:
    paths:
      - latest-release.md
    branches:
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
