# This is a basic workflow to help you get started with Actions

name: CI

# on:
#   push:
#     tags:        
#       - v1             # Push events to v1 tag
#       - v1.* 
# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]
            
  
#   push:
#     branches: [ master ]
#     tags:
#       - '*'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
        echo Hello, world!
        echo ${{ github.event_name }}
        echo ${{ github }}
        echo ${{ github.event.tag_name }}
        echo ${{ github.event.name }}
        echo ${{ github.event.target_commitish }}
        
